version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"  # Mejor rendimiento para plugins
      MEMORY: "4G"
      ONLINE_MODE: "FALSE"  # Permite jugadores sin cuenta de Mojang (necesario para AuthMe)
      ENABLE_RCON: "true"
      RCON_PASSWORD: "THESECUREPASSWORD"
      SERVER_NAME: "SurvivalDayZ"
    volumes:
      - ./data:/data  # Guarda todos los archivos del servidor
    stdin_open: true
    tty: true
